web/router.ex
defmodule Photographer.Router do
  use Photographer.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :browser_session do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Photographer do
    pipe_through [:browser, :browser_session] # Use the default browser stack

    get "/", PageController, :index
    post "/send_message", PageController, :send_message, as: :send_message
    resources "/admin/categories", Admin.CategoryController
    resources "/admin/photos", Admin.PhotoController

    get "/admin/login", Admin.SessionController, :new, as: :login
    post "/admin/login", Admin.SessionController, :create, as: :login
    delete "/admin/logout", Admin.SessionController, :delete, as: :logout
    get "/admin/logout", Admin.SessionController, :delete, as: :logout
  end

  # Other scopes may use custom stacks.
  # scope "/api", Photographer do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule Photographer.LayoutView do
  use Photographer.Web, :view
end

web/templates/layout/admin.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Photographer</title>

    <link rel="stylesheet" href="<%= static_path(@conn, "/css/vendor.css") %>">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/admin/app.css") %>">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Photographer</a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="<%= logout_path(@conn, :delete) %>">Signout</a></li>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-3 col-md-2 sidebar">
        <ul class="nav nav-sidebar">
          <li class="<%= view_module(@conn) == Photographer.Admin.PhotoView && 'active' || '' %>"><a href="<%= photo_path(@conn, :index) %>">Photos <span class="sr-only">(current)</span></a></li>
          <li class="<%= view_module(@conn) == Photographer.Admin.CategoryView && 'active' || '' %>"><a href="<%= category_path(@conn, :index) %>">Categories</a></li>
        </ul>
      </div>
      <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">

        <%= @inner %>

      </div>
    </div>
  </div>

  <script src="<%= static_path(@conn, "/js/admin/vendor.js") %>"></script>
  <script src="<%= static_path(@conn, "/js/admin/app.js") %>"></script>
  </body>
</html>

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<title>Evgeniya Morskova</title>

<!-- Google fonts -->
<link href='//fonts.googleapis.com/css?family=Roboto:400,300,700' rel='stylesheet' type='text/css'>

<!-- font awesome -->
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

<!-- favicon -->
<link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">
<link rel="icon" href="images/favicon.ico" type="image/x-icon">

<link rel="stylesheet" href="<%= static_path(@conn, "/css/vendor.css") %>">
<link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">

</head>

<body>

<%= @inner %>

<script src="<%= static_path(@conn, "/js/vendor.js") %>"></script>
<script src="<%= static_path(@conn, "/js/app.js") %>"></script>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-51865164-2', 'auto');
  ga('send', 'pageview');
</script>
</body>
</html>