web/router.ex
defmodule Photographer.Router do
  use Photographer.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :browser_session do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Photographer do
    pipe_through [:browser, :browser_session] # Use the default browser stack

    get "/", PageController, :index
    post "/send_message", PageController, :send_message, as: :send_message
    resources "/admin/categories", Admin.CategoryController
    resources "/admin/photos", Admin.PhotoController

    get "/admin/login", Admin.SessionController, :new, as: :login
    post "/admin/login", Admin.SessionController, :create, as: :login
    delete "/admin/logout", Admin.SessionController, :delete, as: :logout
    get "/admin/logout", Admin.SessionController, :delete, as: :logout
  end

  # Other scopes may use custom stacks.
  # scope "/api", Photographer do
  #   pipe_through :api
  # end
end

web/templates/page/index.html.eex
<div class="topbar animated fadeInLeftBig"></div>

<!-- Header Starts -->
<div class="navbar-wrapper">
      <div class="container">

        <div class="navbar navbar-default navbar-fixed-top" role="navigation" id="top-nav">
          <div class="container">
            <div class="navbar-header">
              <!-- Logo Starts -->
              <a class="navbar-brand" href="#home" style="font-size: 33px; margin-top: 17px;">
                <!-- <img src="images/logo.png" alt="logo"> -->
                Evgeniya Morskova
              </a>
              <!-- #Logo Ends -->
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
            </div>
            <!-- Nav Starts -->
            <div class="navbar-collapse  collapse">
              <ul class="nav navbar-nav navbar-right scroll">
                 <li class="active"><a href="#works">Home</a></li>
                 <li ><a href="#about">About</a></li>
                 <li ><a href="#contact">Contact</a></li>
              </ul>
            </div>
            <!-- #Nav Ends -->

          </div>
        </div>

      </div>
    </div>
<!-- #Header Starts -->

<!-- works -->
<div id="works" class="clearfix grid">
  <%= for {category, cover} <- @categories do %>
    <figure class="effect-oscar wowload fadeInUp">
      <img src="images/portfolio/<%= cover %>" alt=""/>
        <figcaption>
            <h2><%= category.title %></h2>
            <p><br>
            <%= for photo <- category.photos do %>
                <a href="images/portfolio/<%= photo.file %>" title="<%= photo.description %>" data-gallery="#<%= category.title %>">View more</a>
            </p>
            <% end %>
        </figcaption>
    </figure>
  <% end %>
</div>
<!-- works -->

<!-- Cirlce Starts -->
<div id="about"  class="container spacer about">
<h2 class="text-center wowload fadeInUp">About me</h2>
  <div class="row">
    <div class="col-sm-12 wowload fadeInLeft">
      <h4><i class="fa fa-camera"></i>Photography</h4>
      <p>Hello! My name is Evgeniya. I'm keen on photography. Here is some of my works.</p>
    </div>
  </div>

</div>
<!-- #Cirlce Ends -->

</div>

<!--Contact Starts-->
<div id="contact" class="spacer">

<div class="container contactform center">
<h2 class="text-center wowload fadeInUp">Send me a message</h2>
  <div class="row wowload fadeInLeftBig">
      <div class="col-sm-6 col-sm-offset-3 col-xs-12">
        <%= form_tag(send_message_path(@conn, :send_message)) do %>
          <input type="text" placeholder="Name" name="name">
          <textarea rows="5" placeholder="Message" name="message"></textarea>
          <button type="submit" class="btn btn-primary"><i class="fa fa-paper-plane"></i> Send</button>
        <%= end %>
      </div>
  </div>
</div>
</div>
<!--Contact Ends-->

<!-- Footer Starts -->
<div class="footer text-center spacer">
  <p class="wowload flipInX">
  <a href="https://www.facebook.com/profile.php?id=100001734268108" target="_blank"><i class="fa fa-facebook fa-2x"></i></a>
  <a href="https://www.instagram.com/evgeniya_morskova" target="_blank"><i class="fa fa-instagram fa-2x"></i></a>
  <a href="https://www.flickr.com/photos/morskova" target="_blank"><i class="fa fa-flickr fa-2x"></i></a>
  </p>
Copyright 2016 Evgeniya Morskova. All rights reserved.
</div>
<!-- # Footer Ends -->
<a href="#works" class="gototop "><i class="fa fa-angle-up  fa-3x"></i></a>


<!-- The Bootstrap Image Gallery lightbox, should be a child element of the document body -->
<div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls">
    <!-- The container for the modal slides -->
    <div class="slides"></div>
    <!-- Controls for the borderless lightbox -->
    <h3 class="title">Title</h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <!-- The modal dialog, which will be used to wrap the lightbox content -->
</div>